# Generated by Django 5.0.5 on 2024-07-10 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ImageModel",
        ),
    ]
